### ISSUE TITLE
Issue with docs.zowe.org/stable/extend/extend-apiml/authentication-for-apiml-services

### ISSUE THREAD

**Issue by dkelosky** [zowe/docs-site#3482]
## Description

Can we provide info to our users on how to make the decision on which provider to use?  For example, if you have z/OSMF, and want to access it's APIs via the API ML, you should use provider `zosmf`.  If you are configuring for a system or sysplex where z/OSMF does not run, you need to use provider `saf`.  

Obviously not that exact wording but perhaps something similar could instruct users how to chose rather than what the choices are?  

## Pages to Update

https://docs.zowe.org/stable/extend/extend-apiml/authentication-for-apiml-services#authentication-providers

**Comment by balhar-jakub** [comment]
I agree, but I would argue that this whole section, belongs under Advanced API ML Configuration, it doesn't concern Extenders at all, am I correct?

Maybe the dummy provider for quick start for development could belong into an article in Extending on Quick Start API ML for development. 

## Authentication providers

API ML contains the following providers to handle authentication for the API Gateway:
* `z/OSMF Authentication Provider`
* `SAF Authentication Provider`
* `Dummy Authentication Provider`

z/OSMF Authentication Provider should be used in most cases. The z/OSMF is part of the z/OS and as such is the best option for providing the authentication API. 

The SAF Authentication provider should be used when z/OSMF isn't available. In that case API Gateway acts as the authentication service. The provided credentials are validated directly by API Gateway via SAF APIs. 

### z/OSMF Authentication Provider

The `z/OSMF Authentication Provider` allows the API Gateway to authenticate with the z/OSMF service. The user needs z/OSMF access in order to authenticate.

Use the following properties of the API Gateway to enable the `z/OSMF Authentication Provider`:
```
apiml.security.auth.provider: zosmf
apiml.security.auth.zosmfServiceId: zosmf  # Replace me with the correct z/OSMF service id
```
### SAF Authentication Provider

The `SAF Authentication Provider` allows the API Gateway to authenticate directly with the z/OS SAF provider that is installed on the system. The user needs a SAF account to authenticate. 

Use the following property of the API Gateway to enable the `SAF Authentication Provider`:
```
apiml.security.auth.provider: saf
```
**Note:** To provide your own implementation of the SAF IDT provider, see the [Implement new SAF provider](implement-new-saf-provider.md) guidelines.

### Dummy Authentication Provider

The `Dummy Authentication Provider` implements simple authentication for development purposes using dummy credentials (username:  `user`, password `user`). The `Dummy Authentication Provider` makes it possible for the API Gateway to run without authenticating with the z/OSMF service.

Use the following property of API Gateway to enable the `Dummy Authentication Provider`:
```
apiml.security.auth.provider: dummy
```

**Comment by dkelosky** [comment]
> I agree, but I would argue that this whole section, belongs under Advanced API ML Configuration, it doesn't concern Extenders at all, am I correct?

Good point, I agree.

I think the proposed changes and way you describe the guidance is very helpful as it describe "how" to choose a provider.  Thanks!

**Comment by janan07** [comment]
This has been addressed in https://github.com/zowe/docs-site/pull/3500

**Comment by balhar-jakub** [comment]
Part of it was, the second part is to move it under Advanced Configuration and that part is still missing. 

First we need to create new Page - Authentication Providers for API Mediation Layer and move the content there and then in the current place we need to link to the new location so that it's available for those who go to the current location.

**Comment by janan07** [comment]
This issue has been addressed with PR[#3523](https://github.com/zowe/docs-site/pull/3523/files)

**Comment by balhar-jakub** [comment]
As such I am closing the issue
